### ISSUE TITLE
cffi missing from dependencies

### ISSUE THREAD

**Issue by fossum** [naim94a/vix#11]
```
(vix_env) eric@ERICPC3 C:\dev
> pip install vix
Collecting vix
  Downloading vix-1.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\eric\AppData\Local\Temp\pip-build-smmf_sy2\vix\setup.py", line 2, in <module>
        from vix import __version__
      File "C:\Users\eric\AppData\Local\Temp\pip-build-smmf_sy2\vix\vix\__init__.py", line 13, in <module>
        from .VixBackend import VixBackend as _VixBackend
      File "C:\Users\eric\AppData\Local\Temp\pip-build-smmf_sy2\vix\vix\VixBackend.py", line 2, in <module>
        import cffi
    ModuleNotFoundError: No module named 'cffi'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\eric\AppData\Local\Temp\pip-build-smmf_sy2\vix\

(vix_env) eric@ERICPC3 C:\dev
> pip install cffi
Collecting cffi
  Downloading cffi-1.10.0-cp36-cp36m-win32.whl (149kB)
    100% |████████████████████████████████| 153kB 502kB/s
Collecting pycparser (from cffi)
  Downloading pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 387kB/s
Building wheels for collected packages: pycparser
  Running setup.py bdist_wheel for pycparser ... done
  Stored in directory: C:\Users\eric\AppData\Local\pip\Cache\wheels\95\14\9a\5e7b9024459d2a6600aaa64e0ba485325aff7a9ac7489db1b6
Successfully built pycparser
Installing collected packages: pycparser, cffi
Successfully installed cffi-1.10.0 pycparser-2.18

(vix_env) eric@ERICPC3 C:\dev
> pip install vix
Collecting vix
  Using cached vix-1.0.5.tar.gz
Requirement already satisfied: cffi>=1.8.2 in c:\dev\vix_env\lib\site-packages (from vix)
Requirement already satisfied: pycparser in c:\dev\vix_env\lib\site-packages (from cffi>=1.8.2->vix)
Building wheels for collected packages: vix
  Running setup.py bdist_wheel for vix ... done
  Stored in directory: C:\Users\eric\AppData\Local\pip\Cache\wheels\5c\bc\f8\a9f27fc73d691cb33ed2ace5f586865308aeff589f9b6fd03e
Successfully built vix
Installing collected packages: vix
Successfully installed vix-1.0.5

(vix_env) eric@ERICPC3 C:\dev
>
```

**Comment by naim94a** [comment]
This issue was already resolved in master, but not in pypi...
