### ISSUE TITLE
Error: The specified version was not found

### ISSUE THREAD

**Issue by 0x410c** [naim94a/vix#15]
`
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from vix import VixHost,VixError
>>> host = VixHost()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27-x64\lib\site-packages\vix\VixHost.py", line 141, in __init__
    raise VixError(vix.VixJob_GetError(job))
vix.VixError.VixError: VixError #22002: The specified version was not found`

this is what i get on windows 10 vmware workstation 15, any way i can make it work?

**Comment by 0x410c** [comment]
for future explorers:
this not the problem of this library

in the vix installation path i.e
`C:\Program Files (x86)\VMware\VMware VIX`

in file **vixwrapper-config.txt** replace this
```
# latest un-versioned
ws        19  vmdb  e.x.p Workstation-15.0.0
player    19  vmdb  e.x.p Workstation-15.0.0
```

with
```
# latest un-versioned
ws        19  vmdb  15.5.0 Workstation-15.0.0
player    19  vmdb  15.5.0 Workstation-15.0.0
```
